### ISSUE TITLE
roadmap?

### ISSUE THREAD

**Issue by alexisargyris** [brokensandals/notesdir#1]
Hi!

Congrats for focusing on the core notes management functionality instead of UI, etc. What is your roadmap? Do you plan, for example, to package your work as a VS Code plugin?

**Comment by brokensandals** [comment]
Thanks! I want to keep the project editor-independent, but I do currently use VS Code and will probably make a plugin to provide a few conveniences there, like:

- making the CLI commands accessible from the command palette
- providing a nicer query interface

It might also provide miscellaneous features to help with editing notes, such as pasting in attachments or quickly inserting Markdown links, although my hope is that existing extensions fill most of those needs or that non-notesdir-specific extensions can be created (for example, https://github.com/brokensandals/paste-relative-path). The main motivation for this project is to store notes in a way that allows one to take advantage of a wide range of existing software.

**Comment by alexisargyris** [comment]
Fully agree on the "less is more" approach. All the best!
