### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by kevinslin** [brokensandals/notesdir#2]
does notesdir support windows?

**Comment by brokensandals** [comment]
I've only tested on Mac, but it's intended to work cross-platform*. If you run into any issues on Windows, let me know and I'll try to look into it!

\* The unit tests do use forward slashes in pathnames, so those might not run on Windows - if not I should fix that. I tried to avoid making those kind of assumptions in the main code though.

**Comment by kevinslin** [comment]
I tried it on Mac and it works well but haven't been able to get anything on windows. 

below is output of running `notesdir info`

![](https://foundation-prod-assetspublic53c57cce-8cpvgjldwysl.s3-us-west-2.amazonaws.com/assets/images/notesdir.jpg)

**Comment by brokensandals** [comment]
Can you try using standard markdown link syntax (like `[whatever](bar.md)`), to confirm whether it's a general issue or specific to the wiki-style links?

I just tested and it seems to work for me:

<img width="378" alt="Screen Shot 2020-08-09 at 1 00 58 AM" src="https://user-images.githubusercontent.com/328868/89727736-5af10980-d9dc-11ea-9382-3d5b4195c907.png">

**Comment by kevinslin** [comment]
hey, this is just an heartbeat to let you know i'm still planning on verifying. been a crazy week but will dig into this again this weekend!

**Comment by kevinslin** [comment]
okay, can't reproduce. going to close
